<div class="container py-8">
    <p><strong>GUAPISSIMA COSMETICS</strong>, en cumplimiento a las disposiciones aplicables de la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares, su Reglamento y dem&aacute;s ordenamientos aplicables (la "Ley"), pone a su disposici&oacute;n el presente aviso de privacidad (el "Aviso de Privacidad").</p>
    <p>Se consideran como datos personales cualquier informaci&oacute;n concerniente a una persona f&iacute;sica, que la identifique o que pueda ser asociada a una persona identificable (los "Datos Personales").</p>
    <p>GUAPISSIMA COSMETICS protege la privacidad y es el responsable del tratamiento de los Datos Personales que proporciona su titular (el "Titular").</p>
    <p>GUAPISSIMA COSMETICS cuenta con los mecanismos tecnol&oacute;gicos, f&iacute;sicos, administrativos y legales para proteger la informaci&oacute;n y Datos Personales del Titular, adem&aacute;s de que GUAPISSIMA COSMETICS aplica las mejores pr&aacute;cticas internacionales en el manejo y administraci&oacute;n de los Datos Personales. En todo caso, GUAPISSIMA COSMETICS administra los Datos Personales del Titular con altos est&aacute;ndares de &eacute;tica, responsabilidad y profesionalismo.</p>
    <p>GUAPISSIMA COSMETICS no vende, cede o lucra en formar alguna los Datos Personales con terceros, pero GUAPISSIMA COSMETICS si podr&aacute; compartir los Datos Personales con sus Partes Relacionadas, como dicho t&eacute;rmino se define m&aacute;s adelante, y/o a sus prestadores de servicios para los t&eacute;rminos establecidos en este Aviso de Privacidad y de acuerdo con la finalidad del tratamiento de los Datos Personales.</p>
    <p>El Aviso de Privacidad est&aacute; dirigido a cualquier Titular que proporcione sus Datos Personales en virtud de los siguiente: (1) Los clientes que realizan compras en las Tiendas GUAPISSIMA COSMETICS; (2) Los clientes y/o usuarios que realizan compras o utilizan la p&aacute;gina web localizada en http://GUAPISSIMAONLINE.com/ (en adelante "Sitio Web"), y (3) Cualquier persona que haga uso de las redes sociales administradas por GUAPISSIMA COSMETICS y otros posibles medios de comunicaci&oacute;n, encuestas presenciales en eventos propios o de terceros, as&iacute; como para informaci&oacute;n recopilada por cualquier otro medio.</p>
    <ol>
    <li><strong> TIPO DE INFORMACI&Oacute;N RECOPILADA </strong></li>
    </ol>
    <p>En cumplimiento a la Ley, GUAPISSIMA COSMETICS podr&aacute; recopilar los datos que a continuaci&oacute;n se se&ntilde;alan.</p>
    <ol>
    <li>a) Datos de identificaci&oacute;n: informaci&oacute;n que permite diferenciar al Titular de otros individuos. Los datos que se pueden solicitar se mencionan de forma enunciativa m&aacute;s no limitativa: nombre, t&iacute;tulo, firma aut&oacute;grafa, firma electr&oacute;nica, registro federal de contribuyentes (RFC), identificaci&oacute;n oficial, pa&iacute;s de nacimiento, ciudad de residencia, edad y cualesquiera otros datos que GUAPISSIMA COSMETICS recolecte de tiempo en tiempo.</li>
    <li>b) Datos de contacto: informaci&oacute;n que nos permite mantener comunicaci&oacute;n con el Titular. Los datos pueden incluir informaci&oacute;n sobre domicilio, domicilio fiscal, domicilio para efectos de realizar entregas, correo electr&oacute;nico, tel&eacute;fono particular, tel&eacute;fono de contacto y otros datos de contacto.</li>
    <li>c) Datos patrimoniales o financieros: GUAPISSIMA COSMETICS podr&aacute; solicitar datos de la tarjeta de d&eacute;bito o cr&eacute;dito para completar cualquier transacci&oacute;n realizada por el Titular por la adquisici&oacute;n de cualquier servicio GUAPISSIMA COSMETICS. Asimismo, GUAPISSIMA COSMETICS podr&aacute; conservar la informaci&oacute;n de la (s) tarjeta (s) del Titular para el seguimiento de los procesos de pago relacionados con la adquisici&oacute;n de servicios GUAPISSIMA COSMETICS.</li>
    <li>d) Registros electr&oacute;nicos: esta informaci&oacute;n incluye datos de las compras de servicios GUAPISSIMA COSMETICS, direcci&oacute;n IP para acceder al Sitio Web, preferencias del Titular, tipo de navegador, actividad en el Sitio Web, URL, hit, p&aacute;gina, archivo, visitante (direcci&oacute;n IP o http cookie), visita, host, navegador (web browser), datos que pudieren usar o requerir herramientas de an&aacute;lisis de h&aacute;bitos de navegaci&oacute;n tales como Google Analytics, Etc.</li>
    </ol>
    <p>El Titular se obliga a que los Datos Personales sean ver&iacute;dicos, completos, exactos, as&iacute; como a tener la propiedad y el derecho para proporcionarlos y hacer uso de ellos. Cualquier dato falso, incompleto, inexacto o que necesite la autorizaci&oacute;n de un tercero ser&aacute; exclusiva responsabilidad del Titular, por lo que en este acto libera a GUAPISSIMA COSMETICS de cualquier tipo de responsabilidad que derive por omisi&oacute;n del Titular a lo establecido en el presente p&aacute;rrafo.</p>
    <ol start="2">
    <li><strong> USO DE LA INFORMACI&Oacute;N RECOPILADA </strong></li>
    </ol>
    <p>Los Datos Personales recopilados por GUAPISSIMA COSMETICS son utilizados, de forma general, para procesar las solicitudes, transacciones, proporcionar servicios, informar sobre nuevos servicios y en general para dar a conocer cualquier informaci&oacute;n de utilidad al Titular. Algunos otros usos son:</p>
    <ol>
    <li>a) Procesar solicitudes y pagos por compra de servicios de GUAPISSIMA COSMETICS, as&iacute; como para evaluar el m&eacute;todo de pago, prevenir fraudes y coordinar la entrega del pedido de cualquier servicio.</li>
    <li>b) Procesar los Datos Personales del titular para emitir facturas, procesar devoluciones de servicios, administrar el historial de las transacciones del titular, dar seguimiento a aclaraciones e investigaciones y administrar cualquier programa de mercadotecnia de GUAPISSIMA COSMETICS.</li>
    <li>c) Establecer comunicaci&oacute;n con el titular por cualquier motivo que derive de la relaci&oacute;n comercial con GUAPISSIMA COSMETICS, incluyendo aspectos relacionados con la entrega de los pedidos de servicios, seguimientos a cualquier aclaraci&oacute;n o notificar cualquier modificaci&oacute;n sobre los servicios de GUAPISSIMA COSMETICS.</li>
    <li>d) Para enviar al titular cualquier tipo de informaci&oacute;n promocional tales como publicaciones, encuestas, ofertas y recomendaciones por parte de GUAPISSIMA COSMETICS.</li>
    </ol>
    <p>El Titular tiene la facultad, en cualquier momento, para rechazar la recepci&oacute;n de cualquier informaci&oacute;n por parte de GUAPISSIMA COSMETICS, sin que lo anterior afecte la relaci&oacute;n comercial para la adquisici&oacute;n de nuevos servicios de GUAPISSIMA COSMETICS.</p>
    <p>GUAPISSIMA COSMETICS recolecta los Datos Personales del Titular cumpliendo, en todo momento, con los principios de licitud, calidad, consentimiento, informaci&oacute;n, finalidad, lealtad, proporcionalidad y responsabilidad, conforme lo marca la Ley.</p>
    <ol start="3">
    <li><strong> TRANSFERENCIA DE LA INFORMACI&Oacute;N RECOPILADA </strong></li>
    </ol>
    <p>GUAPISSIMA COSMETICS se reserva la facultad de compartir y/o transferir los Datos Personales a terceros, de conformidad con lo que se establecen a continuaci&oacute;n.</p>
    <ol>
    <li><strong>a) A terceros</strong>: GUAPISSIMA COSMETICS podr&aacute; transmitir sus Datos Personales a terceros que le prestan alg&uacute;n servicio, incluyendo sin limitar, proveedores relacionados con las operaciones de comercio electr&oacute;nico que incluyen el procesamiento de pago a trav&eacute;s de tarjetas de d&eacute;bito y/o cr&eacute;dito, el env&iacute;o de servicio, env&iacute;o de correos electr&oacute;nicos, entre otros. Para tal efecto, GUAPISSIMA COSMETICS solicitar&aacute; a sus proveedores que utilice exclusivamente los Datos Personales en la medida que resulten necesarios para la relaci&oacute;n comercial entre GUAPISSIMA COSMETICS y el Titular. En este sentido, sus datos pueden ser transferidos a los siguientes proveedores que se mencionan de forma enunciativa m&aacute;s no limitativa:</li>
    </ol>
    <p>(i) Proveedores de servicios de procesamiento de pagos y prevenci&oacute;n de fraude. Respecto de las operaciones realizadas con tarjeta de cr&eacute;dito o d&eacute;bito la informaci&oacute;n que se entregar&aacute; tendr&aacute; los siguientes fines que se mencionan de forma enunciativa m&aacute;s no limitativa: para procesar los pagos de las transacciones con GUAPISSIMA COSMETICS, para proporcionar a la entidad bancaria correspondiente la informaci&oacute;n sobre la tarjeta y las particularidades de la operaci&oacute;n, para informaci&oacute;n al emisor de la tarjeta o a la entidad bancaria para identificar riesgos de fraude relacionados con la tarjeta utilizada para las transacciones de los servicios GUAPISSIMA COSMETICS, entre otros.</p>
    <p>(ii) Empresas de mensajer&iacute;a y/o log&iacute;stica. GUAPISSIMA COSMETICS podr&aacute; compartir los Datos Personales a las empresas de mensajer&iacute;a y log&iacute;stica con las que GUAPISSIMA COSMETICS colabora para el proceso de entrega al Titular de los servicios GUAPISSIMA COSMETICS adquiridos, procesos de devoluciones, entre otros.</p>
    <p>Asimismo, GUAPISSIMA COSMETICS solicita a los terceros que mantengan la confidencialidad respecto de los Datos Personales y, una vez que dicha informaci&oacute;n no sea utilizada, la regresen a GUAPISSIMA COSMETICS o, en su caso, la eliminen de sus bases de datos.</p>
    <ol>
    <li>b) A los accionistas:, subsidiarias y/o afiliadas, directivos, consejeros, funcionarios, empleados, asesores y/o representantes de GUAPISSIMA COSMETICS (las "Partes Relacionadas") podr&aacute;n tener acceso a los Datos Personales del Titular para el cumplimiento de los fines del Aviso de Privacidad.</li>
    <li>c) Otro uso de los Datos Personales: GUAPISSIMA COSMETICS podr&aacute; usar o divulgar sus Datos Personales, de buena fe, en los casos que establezca la Ley, mencionando sin limitar, en caso de que se le requiera a GUAPISSIMA COSMETICS cumplir con alg&uacute;n requerimiento de autoridad o alg&uacute;n proceso legal, dar seguimiento a reclamaciones o proteger la integridad de GUAPISSIMA COSMETICS y sus Partes Relacionadas.</li>
    </ol>
    <p>GUAPISSIMA COSMETICS compartir&aacute; con terceros, &uacute;nica y exclusivamente, la informaci&oacute;n necesaria para la realizaci&oacute;n de la relaci&oacute;n comercial con el Titular, oblig&aacute;ndose a mantener la confidencialidad respecto de dicha informaci&oacute;n y no utilizarla para ning&uacute;n fin distinto.</p>
    <p>Si por cualquier raz&oacute;n usted no est&aacute; de acuerdo en la transferencia de sus Datos Personales, podr&aacute; ejercer sus derechos ARCO conforme al procedimiento establecido para tal efecto en el presente Aviso de Privacidad.</p>
    <ol start="4">
    <li><strong> DERECHOS ARCO </strong></li>
    </ol>
    <p>El Titular podr&aacute; ejercer sus derechos ARCO (Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y Oposici&oacute;n) as&iacute; como revocar su consentimiento para el tratamiento de sus Datos Personales en cualquier momento, contactando directamente a GUAPISSIMA COSMETICS al correo electr&oacute;nico ___________________________________x.</p>
    <p>La solicitud deber&aacute; contener la informaci&oacute;n que se se&ntilde;ala a continuaci&oacute;n, independientemente de lo establecido en el art&iacute;culo 29 de la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares.</p>
    <p>(i) Datos del titular: Nombre Completo, Domicilio Completo, Tel&eacute;fono y Correo electr&oacute;nico (donde se le comunicar&aacute; la respuesta a su solicitud).</p>
    <p>(ii) Informaci&oacute;n del representante legal (en caso de aplicar): Nombre Completo, y en caso de ser representante legal del titular deber&aacute; acompa&ntilde;ar a su escrito el instrumento p&uacute;blico correspondiente en original, o en su caso, carta poder firmada ante dos testigos.</p>
    <p>(iii) Derechos ARCO: Indicar el (los) derecho (s) que desea ejercer: Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y/u Oposici&oacute;n. Asimismo, se deber&aacute; hacer una descripci&oacute;n de los Datos Personales respecto de los que se busca ejercer el (los) derecho (s) se&ntilde;alados anteriormente y/o cualquier otro comentario que nos ayude a atender mejor su derecho.</p>
    <p>(iv) Otra Documentaci&oacute;n necesaria: La documentaci&oacute;n que respalde la solicitud deber&aacute; adjuntarse en copia simple, por ejemplo, en la solicitud de rectificaci&oacute;n de Datos Personales se deber&aacute; relacionar y adjuntar el dato incorrecto, el dato correcto y el documento acreditativo.</p>
    <p>En caso de que la informaci&oacute;n proporcionada en la solicitud sea err&oacute;nea o insuficiente, o bien, no se acompa&ntilde;en los documentos de acreditaci&oacute;n correspondientes, GUAPISSIMA COSMETICS podr&aacute; requerir al Titular que subsane lo que resulte necesario dentro de los 10 (diez) d&iacute;as h&aacute;biles siguientes a la fecha de la recepci&oacute;n de la solicitud. En ese supuesto, el Titular contar&aacute; con 10 (diez) d&iacute;as h&aacute;biles, contados a partir del requerimiento de GUAPISSIMA COSMETICS, para subsanar o rectificar la solicitud correspondiente, de lo contrario, en caso de que no se subsane lo solicitado en dicho plazo, la solicitud se tendr&aacute; por no presentada.</p>
    <p>GUAPISSIMA COSMETICS comunicar&aacute; al Titular la resoluci&oacute;n adoptada dentro de un plazo de 20 (veinte) d&iacute;as h&aacute;biles siguientes contados a partir de la fecha en que haya recibido la solicitud o a partir de que la fecha en que el titular haya subsanado el requerimiento realizado por GUAPISSIMA COSMETICS, seg&uacute;n corresponda. La resoluci&oacute;n ser&aacute; efectiva dentro de los 15 (quince) d&iacute;as h&aacute;biles siguientes a partir de la fecha de notificaci&oacute;n de la resoluci&oacute;n que corresponda. La resoluci&oacute;n se dar&aacute; por la misma v&iacute;a en que nos envi&oacute; su solicitud.</p>
    <ol start="5">
    <li><strong> MODIFICACIONES</strong></li>
    </ol>
    <p>GUAPISSIMA COSMETICS se reserva el derecho de cambiar el contenido del presente Aviso de Privacidad en cualquier momento. En caso de que exista alg&uacute;n cambio en este Aviso de Privacidad, GUAPISSIMA COSMETICS lo comunicar&aacute; de la siguiente manera: (a) enviando un correo electr&oacute;nico a la cuenta registrada por el Titular en el Sitio Web o por cualquier otro medio presencial y/o electr&oacute;nico de recolecci&oacute;n de datos, (b) publicando una nota visible en cualquier parte del Sitio Web, en este acto el Titular acepta que la notificaci&oacute;n de las modificaciones al Aviso de Privacidad surtir&aacute;n sus efectos desde el momento en que GUAPISSIMA COSMETICS las publique en el Sitio Web.</p>
    <p>GUAPISSIMA COSMETICS no ser&aacute; responsable si el Titular no recibe la notificaci&oacute;n de cambio en el Aviso de Privacidad, por alg&uacute;n problema con los datos de la cuenta de correo electr&oacute;nico o de transmisi&oacute;n de datos por internet proporcionados por el Titular. El Titular acepta y se obliga a revisar de tiempo en tiempo el contenido de este Aviso de Privacidad en el Sitio Web.</p>
    <ol start="6">
    <li><strong> RESOLUCI&Oacute;N DE CONTROVERSIAS </strong></li>
    </ol>
    <p>En caso de que se presente una controversia que se derive del presente Aviso de Privacidad, las partes intentar&aacute;n primero resolverla a trav&eacute;s de negociaciones de buena fe, pudiendo ser asistidos por un mediador profesional. Si despu&eacute;s de un m&aacute;ximo de 30 (treinta) d&iacute;as h&aacute;biles de negociaci&oacute;n, las partes no llegaren a un acuerdo, se estar&aacute; a lo dispuesto por la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares, aceptando las partes la intervenci&oacute;n que pudiere tener el Instituto Federal de Acceso a la Informaci&oacute;n y Protecci&oacute;n de Datos Personales.</p>
    <p><strong>GUAPISSIMA COSMETICS</strong> &mdash; Av. Cuahutemoc #1709 local 3, Colonia Infonavit Cuahutemoc C.P. 64348, Santa Catarina, Nuevo Le&oacute;n, M&eacute;xico</p>
    <p>(correo electr&oacute;nico)</p>
</div>
