<div class="container py-8">
    <ol>
        <li>PROEMIO</li>
        </ol>
        <p>AL INGRESAR Y UTILIZAR ESTE PORTAL DE INTERNET, CUYO NOMBRE DE DOMINIO ES <a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>, PROPIEDAD DE&nbsp;mIREYA AIDE VILLARREAL CARDENAS&nbsp;EN LO SUCESIVO&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;EL USUARIO EST&Aacute; ACEPTANDO LOS T&Eacute;RMINOS Y CONDICIONES DE USO CONTENIDOS EN ESTE CONVENIO Y DECLARA EXPRESAMENTE SU ACEPTACI&Oacute;N UTILIZANDO PARA TAL EFECTO MEDIOS ELECTR&Oacute;NICOS, EN T&Eacute;RMINOS DE LO DISPUESTO POR EL ART&Iacute;CULO 1803 DEL C&Oacute;DIGO CIVIL FEDERAL.</p>
        <p>EN CASO DE NO ACEPTAR EN FORMA ABSOLUTA Y COMPLETA LOS T&Eacute;RMINOS Y CONDICIONES DE ESTE CONVENIO, EL USUARIO DEBER&Aacute; ABSTENERSE DE ACCEDER, UTILIZAR Y OBSERVAR LOS SITIOS WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a></p>
        <p>Y EN CASO DE QUE EL USUARIO ACCEDA, UTILICE Y OBSERVE LOS SITIOS WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>&nbsp;SE CONSIDERAR&Aacute; COMO UNA ABSOLUTA Y EXPRESA ACEPTACI&Oacute;N DE LOS T&Eacute;RMINOS Y CONDICIONES DE USO AQU&Iacute; ESTIPULADOS.</p>
        <p>LA SOLA UTILIZACI&Oacute;N DE DICHA P&Aacute;GINA DE INTERNET LE OTORGA AL P&Uacute;BLICO EN GENERAL LA CONDICI&Oacute;N DE USUARIO (EN ADELANTE REFERIDO COMO EL &laquo;USUARIO&raquo; O LOS &laquo;USUARIOS&raquo;) E IMPLICA LA ACEPTACI&Oacute;N, PLENA E INCONDICIONAL, DE TODAS Y CADA UNA DE LAS CONDICIONES GENERALES Y PARTICULARES INCLUIDAS EN ESTOS T&Eacute;RMINOS Y CONDICIONES DE USO PUBLICADOS POR&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;EN EL MOMENTO MISMO EN QUE EL USUARIO ACCEDA AL SITIO WEB.</p>
        <p>CUALQUIER MODIFICACI&Oacute;N A LOS PRESENTES T&Eacute;RMINOS Y CONDICIONES DE USO SER&Aacute; REALIZADA CUANDO EL TITULAR DE LA MISMA, EN ESTE CASO&nbsp;GUAPISSIMA COSMETICS&reg;, LO CONSIDERE APROPIADO, SIENDO EXCLUSIVA RESPONSABILIDAD DEL USUARIO ASEGURARSE DE TOMAR CONOCIMIENTO DE TALES MODIFICACIONES.</p>
        <ol start="2">
        <li>CONVENIO</li>
        </ol>
        <p>CONVENIO DE ADHESI&Oacute;N PARA EL USO DE LA P&Aacute;GINA DE INTERNET WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>&nbsp;QUE CELEBRAN: POR UNA PARTE,&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;Y, POR LA OTRA, EL USUARIO, SUJET&Aacute;NDOSE, AMBAS PARTES, A LO ESTABLECIDO EN ESTE DOCUMENTO.</p>
        <ol start="3">
        <li>LICENCIA</li>
        </ol>
        <ol>
        <li>POR VIRTUD DE LA CELEBRACI&Oacute;N DE ESTE CONVENIO,&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;OTORGA Y CONCEDE AL USUARIO EL DERECHO NO EXCLUSIVO, REVOCABLE Y NO TRANSFERIBLE DE VER Y UTILIZAR EL SITIO WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>&nbsp;DE CONFORMIDAD CON LOS T&Eacute;RMINOS Y CONDICIONES DE USO QUE AQU&Iacute; SE ESTIPULAN. PARA LOS EFECTOS DEL PRESENTE CONVENIO, LAS PARTES ACUERDAN QUE POR &laquo;USUARIO&raquo; SE ENTENDER&Aacute; A CUALQUIER PERSONA DE CUALQUIER NATURALEZA QUE INGRESE A LOS SITIOS WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>&nbsp;Y/O A CUALQUIERA DE LAS SUBP&Aacute;GINAS QUE DESPLIEGAN SU CONTENIDO Y/O A LA PERSONA DE CUALQUIER NATURALEZA QUE SE D&Eacute; DE ALTA Y/O USE CUALQUIERA DE LOS SERVICIOS QUE SE OFRECEN A TRAV&Eacute;S DE DICHA P&Aacute;GINA.</li>
        <li>EL USUARIO S&Oacute;LO PODR&Aacute; IMPRIMIR Y/O COPIAR CUALQUIER INFORMACI&Oacute;N CONTENIDA O PUBLICADA EN EL SITIO WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>&nbsp;EXCLUSIVAMENTE PARA USO PERSONAL, QUEDA TERMINANTEMENTE PROHIBIDO EL USO COMERCIAL DE DICHA INFORMACI&Oacute;N. EN CASO DE SER PERSONA MORAL SE SUJETAR&Aacute; A LO DISPUESTO POR EL ART&Iacute;CULO 148, FRACCI&Oacute;N IV DE LA LEY FEDERAL DEL DERECHO DE AUTOR.</li>
        <li>LA REIMPRESI&Oacute;N, PUBLICACI&Oacute;N, DISTRIBUCI&Oacute;N, ASIGNACI&Oacute;N, SUBLICENCIA, VENTA, REPRODUCCI&Oacute;N ELECTR&Oacute;NICA O POR OTRO MEDIO, PARCIAL O TOTAL, DE CUALQUIER INFORMACI&Oacute;N, DOCUMENTO O GR&Aacute;FICO QUE APAREZCA EN EL SITIO WEB&nbsp;<a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a>&nbsp;PARA CUALQUIER USO DISTINTO AL PERSONAL NO COMERCIAL LE EST&Aacute; EXPRESAMENTE PROHIBIDO AL USUARIO, A MENOS DE QUE CUENTE CON LA AUTORIZACI&Oacute;N PREVIA Y POR ESCRITO DE&nbsp;GUAPISSIMA COSMETICS&reg;</li>
        </ol>
        <ol start="4">
        <li>REGLAS PARA EL USO DEL SITIO <a href="HTTPS://GUAPISSIMAONLINE.COM.MX/">HTTPS://GUAPISSIMAONLINE.COM.MX/</a></li>
        </ol>
        <p>EL USUARIO Y gUAPISSIMA COSMETICS&reg; EST&Aacute;N DE ACUERDO EN QUE LA UTILIZACI&Oacute;N DEL SITIO WEB&nbsp;<a href="https://bellezaenlinea.com.mx/">HTTPS:// GUAPISSIMAONLINE.COM.MX/</a>&nbsp;SE SUJETAR&Aacute; A LAS SIGUIENTES REGLAS:</p>
        <ol>
        <li>INFORMACI&Oacute;N CONTENIDA EN EL SITIO WEB&nbsp;<a href="https://bellezaenlinea.com.mx/">HTTPS:// GUAPISSIMAONLINE.COM.MX/</a>. EL USUARIO RECONOCE Y ACEPTA QUE LA INFORMACI&Oacute;N PUBLICADA O CONTENIDA EN DICHO SITIO SER&Aacute; CLARAMENTE IDENTIFICADA DE FORMA TAL QUE SE RECONOZCA QUE LA MISMA PROVIENE Y HA SIDO GENERADA POR&nbsp;gUAPISSIMA COSMETICS&reg;&nbsp;O POR SUS PROVEEDORES.</li>
        <li>NO OBSTANTE, LA INFORMACI&Oacute;N, CONCEPTOS Y OPINIONES PUBLICADAS EN DICHO SITIO NO NECESARIAMENTE REFLEJAN LA POSICI&Oacute;N DE&nbsp;GUAPISSIMA COSMETICS&reg;, NI DE SUS EMPLEADOS, OFICIALES, DIRECTORES, ACCIONISTAS, LICENCIATARIOS Y CONCESIONARIOS (EN LO SUCESIVO LOS &laquo;AFILIADOS&raquo;). POR ESTA RAZ&Oacute;N,&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;NO SE HACE RESPONSABLE POR NINGUNA DE LAS INFORMACIONES, OPINIONES Y CONCEPTOS QUE SE EMITAN EN LA P&Aacute;GINA WEB REFERIDA. EN ESTE CASO, SE RECOMIENDA AL USUARIO CONSULTAR CON UN ESPECIALISTA Y/O PROFESIONAL EN LA MATERIA. ASIMISMO,&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;NO SE HACE RESPONSABLE DE LA INFORMACI&Oacute;N CONTENIDA EN LA P&Aacute;GINA DE INTERNET, INCLUIDAS LAS SUBP&Aacute;GINAS, EN EL ENTENDIDO DE QUE EL USO Y SEGUIMIENTO DE LA MISMA ES BAJO RIESGO Y RESPONSABILIDAD DEL USUARIO.</li>
        <li>guapissima cosmetics&reg;&nbsp;SE RESERVA EL DERECHO DE BLOQUEAR EL ACCESO O REMOVER EN FORMA PARCIAL O TOTAL TODA INFORMACI&Oacute;N, COMUNICACI&Oacute;N O MATERIAL QUE A SU EXCLUSIVO JUICIO PUEDA RESULTAR: I) ABUSIVO, DIFAMATORIO U OBSCENO; II) FRAUDULENTO, ARTIFICIOSO O ENGA&Ntilde;OSO; III) VIOLATORIO DE DERECHOS DE AUTOR, MARCAS, CONFIDENCIALIDAD, SECRETOS INDUSTRIALES O CUALQUIER DERECHO DE PROPIEDAD INTELECTUAL DE UN TERCERO; IV) OFENSIVO O; V) QUE DE CUALQUIER FORMA CONTRAVENGA LO ESTABLECIDO EN ESTE CONVENIO. SI EL USUARIO DESEA OBTENER M&Aacute;S INFORMACI&Oacute;N DE UN TEMA EN ESPEC&Iacute;FICO PROVE&Iacute;DO POR&nbsp;guapissima cosmetics&reg;&nbsp;O SUS PROVEEDORES DEBER&Aacute; CONSULTARLO DIRECTAMENTE CON CADA UNO DE ELLOS, SEG&Uacute;N CORRESPONDA, Y/O CON UN ESPECIALISTA EN LA MATERIA.</li>
        <li>EL USUARIO RECONOCE QUE&nbsp;guapissima cosmetics&reg;&nbsp;NO CONTROLA O CENSURA PREVIAMENTE EL CONTENIDO DISPONIBLE EN LA P&Aacute;GINA DE INTERNET. POR TAL MOTIVO,&nbsp;guapissima cosmetics&reg;&nbsp;NO ASUME NINGUNA RESPONSABILIDAD POR EL CONTENIDO PROVISTO A DICHA P&Aacute;GINA POR PROVEEDORES INDEPENDIENTES O AJENOS A (guapissima cosmetics&reg;) Y NO TIENE EL CONTROL EDITORIAL SOBRE EL CONTENIDO, INFORMACI&Oacute;N Y/O MATERIAL GENERADO Y/O PROVISTO POR TERCEROS. TODAS LAS OPINIONES, CONSEJOS, DECLARACIONES, SERVICIOS, OFERTAS U OTRAS INFORMACIONES O CONTENIDOS EXPRESADOS O PUESTOS A DISPOSICI&Oacute;N DEL P&Uacute;BLICO POR TERCEROS PERTENECEN A SU RESPECTIVO AUTOR Y&nbsp;guapissima cosmetics&reg;&nbsp;NO ASUME RESPONSABILIDAD ALGUNA FRENTE A ELLO. DE LA MISMA FORMA,&nbsp;guapissima cosmetics&reg;&nbsp;NO GARANTIZA LA EXACTITUD, VERACIDAD, AMPLITUD Y/O UTILIDAD DE CUALQUIER CONTENIDO PROVISTO POR TALES TERCEROS. ADICIONALMENTE,&nbsp;guapissima cosmetics&reg;&nbsp;NO ES RESPONSABLE NI GARANTIZA LA EXACTITUD, EXHAUSTIVIDAD, VERACIDAD Y/O CONFIABILIDAD DE CUALQUIER OPINI&Oacute;N, INFORMACI&Oacute;N, CONSEJO O DECLARACI&Oacute;N EXPRESADOS POR&nbsp;guapissima cosmetics&reg;&nbsp;A TRAV&Eacute;S DE SU P&Aacute;GINA DE INTERNET Y BAJO NINGUNA CIRCUNSTANCIA&nbsp;guapissima cosmetics&reg;&nbsp;SER&Aacute; RESPONSABLE DE CUALQUIER DA&Ntilde;O Y/O PERJUICIO, DIRECTO O INDIRECTO, CAUSADO EN VIRTUD DE LA CONFIANZA QUE EL USUARIO DEPOSITE EN INFORMACI&Oacute;N OBTENIDA A TRAV&Eacute;S DE SU SITIO WEB.&nbsp;guapissima cosmetics&reg;&nbsp;SE RESERVA EL DERECHO DE SUPRIMIR O MODIFICAR EL CONTENIDO DE ESTA P&Aacute;GINA QUE, A EXCLUSIVO JUICIO DE&nbsp;guapissima cosmetics&reg;, NO CUMPLA CON SUS EST&Aacute;NDARES O QUE PUDIERA RESULTAR CONTRARIO AL ORDENAMIENTO JUR&Iacute;DICO VIGENTE Y, POR CONSIGUIENTE, NO SER&Aacute; RESPONSABLE POR CUALQUIER FALLA O TARDANZA QUE SE GENERE AL ELIMINAR TAL MATERIAL.</li>
        </ol>
        <ol start="5">
        <li>FORMATOS</li>
        </ol>
        <p>LOS USUARIOS RECONOCEN QUE, AL PROPORCIONAR LA INFORMACI&Oacute;N DE CAR&Aacute;CTER PERSONAL REQUERIDA EN ALGUNO DE LOS SERVICIOS QUE SE PRESTAN EN ESTE SITIO WEB, OTORGAN A&nbsp;GUAPISSIMA COSMETICS&reg;&nbsp;LA AUTORIZACI&Oacute;N SE&Ntilde;ALADA EN EL ART&Iacute;CULO 109 DE LA LEY FEDERAL DEL DERECHO DE AUTOR. EN TODOS LOS CASOS, LOS USUARIOS RESPONDER&Aacute;N POR LA VERACIDAD DE LA INFORMACI&Oacute;N PROPORCIONADA A&nbsp;guapissima cosmetics&reg;.</p>
        <p>ASIMISMO, PARA LA PRESTACI&Oacute;N DE SERVICIOS, EL USUARIO SE OBLIGA ADEM&Aacute;S A ACEPTAR LOS T&Eacute;RMINOS Y CONDICIONES ESTIPULADOS PARA TAL EFECTO.</p>
        <ol start="6">
        <li>DERECHOS DE AUTOR Y PROPIEDAD INDUSTRIAL</li>
        </ol>
        <p>guapissima cosmetics&reg;, EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>&nbsp;SUS LOGOTIPOS Y TODO EL MATERIAL QUE APARECE EN DICHO SITIO SON MARCAS, NOMBRES DE DOMINIO, NOMBRES COMERCIALES Y OBRAS ART&Iacute;STICAS PROPIEDAD DE SUS RESPECTIVOS TITULARES Y EST&Aacute;N PROTEGIDOS POR LOS TRATADOS INTERNACIONALES Y LAS LEYES APLICABLES EN MATERIA DE PROPIEDAD INTELECTUAL Y DERECHOS DE AUTOR.</p>
        <p>LOS DERECHOS DE AUTOR SOBRE EL CONTENIDO, ORGANIZACI&Oacute;N, RECOPILACI&Oacute;N, COMPILACI&Oacute;N, INFORMACI&Oacute;N, LOGOTIPOS, FOTOGRAF&Iacute;AS, IM&Aacute;GENES, PROGRAMAS, APLICACIONES, Y EN GENERAL CUALQUIER INFORMACI&Oacute;N CONTENIDA O PUBLICADA EN EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>&nbsp;SE ENCUENTRAN DEBIDAMENTE PROTEGIDOS A FAVOR DE&nbsp;guapissima cosmetics&reg;, SUS AFILIADOS, PROVEEDORES Y/O DE SUS RESPECTIVOS PROPIETARIOS, DE CONFORMIDAD CON LA LEGISLACI&Oacute;N APLICABLE EN MATERIA DE PROPIEDAD INTELECTUAL E INDUSTRIAL.</p>
        <p>SE PROH&Iacute;BE EXPRESAMENTE AL USUARIO MODIFICAR, ALTERAR O SUPRIMIR, YA SEA EN FORMA TOTAL O PARCIAL, LOS AVISOS, MARCAS, NOMBRES COMERCIALES, SE&Ntilde;AS, ANUNCIOS, LOGOTIPOS O EN GENERAL CUALQUIER INDICACI&Oacute;N QUE SE REFIERA A LA PROPIEDAD DE LA INFORMACI&Oacute;N CONTENIDA EN EL SITIO SE&Ntilde;ALADO.</p>
        <p>EN CASO DE QUE EL USUARIO TRANSMITA A&nbsp;guapissima cosmetics&reg;&nbsp;CUALQUIER INFORMACI&Oacute;N, PROGRAMAS, APLICACIONES, SOFTWARE O EN GENERAL CUALQUIER MATERIAL QUE REQUIERA SER LICENCIADO A TRAV&Eacute;S DEL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>, EL USUARIO OTORGA CON ESTE ACTO A&nbsp;guapissima cosmetics&reg;&nbsp;UNA LICENCIA PERPETUA, UNIVERSAL, GRATUITA, NO EXCLUSIVA, MUNDIAL Y LIBRE DE REGAL&Iacute;AS, QUE INCLUYE LOS DERECHOS DE SUBLICENCIAR, VENDER, REPRODUCIR, DISTRIBUIR, TRANSMITIR, CREAR TRABAJOS DERIVADOS, EXHIBIRLOS Y EJECUTARLOS P&Uacute;BLICAMENTE.</p>
        <p>LO ESTABLECIDO EN EL P&Aacute;RRAFO ANTERIOR SE APLICAR&Aacute; IGUALMENTE A CUALQUIER OTRA INFORMACI&Oacute;N QUE EL USUARIO ENV&Iacute;E O TRANSMITA A&nbsp;guapissima cosmetics&reg;, INCLUYENDO, SIN LIMITACI&Oacute;N ALGUNA, IDEAS PARA RENOVAR O MEJORAR EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>, YA SEA QUE &Eacute;STAS HAYAN SIDO INCLUIDAS EN CUALQUIER ESPACIO DE LA P&Aacute;GINA SE&Ntilde;ALADA EN VIRTUD DE OTROS MEDIOS O MODOS DE TRANSMISI&Oacute;N CONOCIDOS O QUE SEAN DESARROLLADOS EN EL FUTURO.</p>
        <p>POR LO ANTERIOR, EL USUARIO RENUNCIA EXPRESAMENTE CON ESTE ACTO A LLEVAR A CABO CUALQUIER ACCI&Oacute;N, DEMANDA O RECLAMACI&Oacute;N EN CONTRA DE&nbsp;guapissima cosmetics&reg;, SUS AFILIADOS O PROVEEDORES POR CUALQUIER ACTUAL O EVENTUAL VIOLACI&Oacute;N DE CUALQUIER DERECHO DE AUTOR O PROPIEDAD INTELECTUAL DERIVADO DE LA INFORMACI&Oacute;N, PROGRAMAS, APLICACIONES, SOFTWARE, IDEAS Y DEM&Aacute;S MATERIAL QUE EL PROPIO USUARIO ENV&Iacute;E AL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>, ES NUESTRA POL&Iacute;TICA ACTUAR CONTRA LAS VIOLACIONES QUE EN MATERIA DE PROPIEDAD INTELECTUAL SE PUDIERAN GENERAR U ORIGINAR SEG&Uacute;N LO ESTIPULADO EN LA LEGISLACI&Oacute;N Y EN OTRAS LEYES DE PROPIEDAD INTELECTUAL APLICABLES, INCLUYENDO LA ELIMINACI&Oacute;N O EL BLOQUEO DEL ACCESO A MATERIAL QUE SE ENCUENTRA SUJETO A ACTIVIDADES QUE INFRINJAN EL DERECHO DE PROPIEDAD INTELECTUAL DE TERCEROS.</p>
        <p>EN CASO DE QUE ALG&Uacute;N USUARIO O TERCERO CONSIDEREN QUE CUALQUIERA DE LOS CONTENIDOS QUE SE ENCUENTREN O SEAN INTRODUCIDOS EN DICHO SITIO (<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>) Y/O CUALQUIERA DE SUS SERVICIOS, VIOLEN SUS DERECHOS DE PROPIEDAD INTELECTUAL DEBER&Aacute;N ENVIAR UNA NOTIFICACI&Oacute;N A LA SIGUIENTE DIRECCI&Oacute;N&nbsp;<a href="mailto:CONTACTO@guapissima.COM.MX">CONTACTO@guapissima.COM.MX</a>, EN LA QUE INDIQUEN: I) DATOS PERSONALES VER&Iacute;DICOS (NOMBRE, DIRECCI&Oacute;N, N&Uacute;MERO DE TEL&Eacute;FONO Y DIRECCI&Oacute;N DE CORREO ELECTR&Oacute;NICO DEL RECLAMANTE); II) FIRMA AUT&Oacute;GRAFA CON LOS DATOS PERSONALES DEL TITULAR DE LOS DERECHOS DE PROPIEDAD INTELECTUAL; III) INDICACI&Oacute;N PRECISA Y COMPLETA DEL (LOS) CONTENIDO (S) PROTEGIDO (S) MEDIANTE LOS DERECHOS DE PROPIEDAD INTELECTUAL SUPUESTAMENTE INFRINGIDOS, AS&Iacute; COMO LA LOCALIZACI&Oacute;N DE DICHAS VIOLACIONES EN EL SITIO WEB REFERIDO; IV) DECLARACI&Oacute;N EXPRESA Y CLARA DE QUE LA INTRODUCCI&Oacute;N DEL (LOS) CONTENIDO (S) INDICADO (S) SE HA REALIZADO SIN EL CONSENTIMIENTO DEL TITULAR DE LOS DERECHOS DE PROPIEDAD INTELECTUAL SUPUESTAMENTE INFRINGIDOS; V) DECLARACI&Oacute;N EXPRESA, CLARA Y BAJO LA RESPONSABILIDAD DEL RECLAMANTE DE QUE LA INFORMACI&Oacute;N PROPORCIONADA EN LA NOTIFICACI&Oacute;N ES EXACTA Y DE QUE LA INTRODUCCI&Oacute;N DEL (LOS) CONTENIDO (S) CONSTITUYE UNA VIOLACI&Oacute;N DE DICHOS DERECHOS.</p>
        <ol start="7">
        <li>MATERIAL PUBLICITARIO</li>
        </ol>
        <p>EL USUARIO RECONOCE Y ACEPTA QUE&nbsp;guapissima cosmetics&reg;&nbsp;ES UNA ORGANIZACI&Oacute;N INDEPENDIENTE DE TERCEROS PATROCINADORES Y ANUNCIANTES CUYA INFORMACI&Oacute;N, IM&Aacute;GENES, ANUNCIOS Y DEM&Aacute;S MATERIAL PUBLICITARIO O PROMOCIONAL (EN LO SUBSECUENTE &laquo;MATERIAL PUBLICITARIO&rsaquo;) PUEDE SER PUBLICADO EN EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>. EL USUARIO RECONOCE Y ACEPTA QUE EL MATERIAL PUBLICITARIO NO FORMA PARTE DEL CONTENIDO PRINCIPAL QUE SE PUBLICA EN DICHO SITIO. ASIMISMO, RECONOCE Y ACEPTA CON ESTE ACTO QUE ESTE MATERIAL SE ENCUENTRA PROTEGIDO POR LAS LEYES QUE EN MATERIA DE PROPIEDAD INTELECTUAL E INDUSTRIAL RESULTEN APLICABLES.</p>
        <ol start="8">
        <li>NEGACI&Oacute;N DE GARANT&Iacute;AS</li>
        </ol>
        <p>EL USUARIO EST&Aacute; DE ACUERDO QUE LA UTILIZACI&Oacute;N DEL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>&nbsp;SE REALIZA BAJO SU PROPIO RIESGO Y QUE LOS SERVICIOS Y PRODUCTOS QUE AH&Iacute; SE PRESTAN Y OFRECEN SE PREV&Eacute;N SOBRE UNA BASE &laquo;TAL CUAL&raquo; Y &laquo;SEG&Uacute;N SEAN DISPONIBLES&raquo;.&nbsp;guapissima cosmetics&reg;&nbsp;NO GARANTIZA QUE LAS P&Aacute;GINAS SE&Ntilde;ALADAS SATISFAGAN LOS REQUERIMIENTOS DEL USUARIO O QUE LOS SERVICIOS QUE EN ELLA SE OFRECEN NO SUFRAN INTERRUPCIONES, SEAN SEGUROS O EST&Eacute;N EXENTOS DE ERRORES.</p>
        <p>guapissima cosmetics&reg;&nbsp;NO GARANTIZA O AVALA EN NINGUNA FORMA LA VERACIDAD, PRECISI&Oacute;N, LEGALIDAD, MORALIDAD O NINGUNA OTRA CARACTER&Iacute;STICA DEL CONTENIDO DEL MATERIAL QUE SE PUBLIQUE EN EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a></p>
        <p>guapissima cosmetics&reg;&nbsp;SE LIBERA DE CUALQUIER RESPONSABILIDAD Y CONDICIONES, TANTO EXPRESAS COMO IMPL&Iacute;CITAS, EN RELACI&Oacute;N CON LOS SERVICIOS E INFORMACI&Oacute;N CONTENIDA O DISPONIBLE EN O A TRAV&Eacute;S DE ESTA P&Aacute;GINA WEB; INCLUYENDO, SIN LIMITACI&Oacute;N ALGUNA:</p>
        <ol>
        <li>LA DISPONIBILIDAD DE USO DEL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a></li>
        <li>LA AUSENCIA DE VIRUS, ERRORES, DESACTIVADORES O CUALQUIER OTRO MATERIAL CONTAMINANTE O CON FUNCIONES DESTRUCTIVAS EN LA INFORMACI&Oacute;N O PROGRAMAS DISPONIBLES EN O A TRAV&Eacute;S DE ESTA P&Aacute;GINA O EN GENERAL CUALQUIER FALLA EN DICHO SITIO.</li>
        <li>NO OBSTANTE, LO ANTERIOR,&nbsp;guapissima cosmetics&reg;&nbsp;O SUS PROVEEDORES PODR&Aacute;N ACTUALIZAR EL CONTENIDO DE LA P&Aacute;GINA CONSTANTEMENTE, POR LO QUE SE SOLICITA AL USUARIO TOMAR EN CUENTA QUE ALGUNAS INFORMACIONES PUBLICITADAS O CONTENIDAS EN O A TRAV&Eacute;S DE ESTE SITIO WEB PUEDEN HABER QUEDADO OBSOLETAS Y/O CONTENER IMPRECISIONES O ERRORES TIPOGR&Aacute;FICOS U ORTOGR&Aacute;FICOS.</li>
        </ol>
        <ol start="9">
        <li>LIMITACIONES A LA RESPONSABILIDAD</li>
        </ol>
        <p>HASTA EL M&Aacute;XIMO PERMITIDO POR LAS LEYES APLICABLES,&nbsp;guapissima cosmetics&reg;&nbsp;NO SER&Aacute; RESPONSABLE, EN NING&Uacute;N CASO, POR DA&Ntilde;OS DIRECTOS, ESPECIALES, INCIDENTALES, INDIRECTOS, O CONSECUENCIALES QUE EN CUALQUIER FORMA SE DERIVEN O SE RELACIONEN CON:</p>
        <ol>
        <li>EL USO O EJECUCI&Oacute;N DEL SITIO&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>, CON EL RETRASO O LA FALTA DE DISPONIBILIDAD DE USO DE&nbsp;guapissima cosmetics&reg;</li>
        <li>LA PROVEEDUR&Iacute;A O FALTA DE ESTA DE SERVICIOS DE CUALQUIER INFORMACI&Oacute;N O GR&Aacute;FICOS CONTENIDOS O PUBLICADOS EN O A TRAV&Eacute;S DEL SITIO SE&Ntilde;ALADO.</li>
        <li>LA ACTUALIZACI&Oacute;N O FALTA DE ACTUALIZACI&Oacute;N DE LA INFORMACI&Oacute;N.</li>
        <li>LA ALTERACI&Oacute;N O MODIFICACI&Oacute;N, TOTAL O PARCIAL, DE LA INFORMACI&Oacute;N DESPU&Eacute;S DE HABER SIDO INCLUIDA EN DICHO SITIO.</li>
        <li>CUALQUIER OTRO ASPECTO O CARACTER&Iacute;STICA DE LA INFORMACI&Oacute;N CONTENIDA O PUBLICADA EN LA P&Aacute;GINA WEB O A TRAV&Eacute;S DE LAS LIGAS QUE EVENTUALMENTE SE INCLUYAN EN ESTE SITIO.</li>
        <li>LA PROVEEDUR&Iacute;A O FALTA DE PROVEEDUR&Iacute;A QUE LOS DEM&Aacute;S SERVICIOS, TODOS LOS SUPUESTOS ANTERIORES SER&Aacute;N VIGENTES, A&Uacute;N EN LOS CASOS EN QUE SE LE HUBIERE NOTIFICADO O AVISADO A&nbsp;guapissima cosmetics&reg;&nbsp;ACERCA DE LA POSIBILIDAD DE QUE SE OCASIONEN DICHOS DA&Ntilde;OS.</li>
        </ol>
        <ol start="10">
        <li>MODIFICACIONES AL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a></li>
        </ol>
        <p>guapissima cosmetics&reg;&nbsp;PODR&Aacute; EN CUALQUIER MOMENTO Y CUANDO LO CONSIDERE CONVENIENTE, SIN NECESIDAD DE AVISAR AL USUARIO, REALIZAR CORRECCIONES, ADICIONES, MEJORAS O MODIFICACIONES AL CONTENIDO, PRESENTACI&Oacute;N, INFORMACI&Oacute;N, SERVICIOS, &Aacute;REAS, BASES DE DATOS Y DEM&Aacute;S ELEMENTOS DE DICHO SITIO, SIN QUE ELLO DE LUGAR NI DERECHO A NINGUNA RECLAMACI&Oacute;N O INDEMNIZACI&Oacute;N, NI QUE ESTO IMPLIQUE RECONOCIMIENTO DE RESPONSABILIDAD ALGUNA A FAVOR DEL USUARIO.</p>
        <ol start="11">
        <li>MODIFICACIONES AL CONVENIO</li>
        </ol>
        <p>guapissima cosmetics&reg;&nbsp;SE RESERVA EL DERECHO DE MODIFICAR LOS T&Eacute;RMINOS Y CONDICIONES DE USO DE ESTE CONVENIO EN CUALQUIER MOMENTO, SIENDO EFECTIVAS DICHAS MODIFICACIONES DE FORMA INMEDIATA POR MEDIO DE:</p>
        <ol>
        <li>LA PUBLICACI&Oacute;N EN EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>&nbsp;DEL CONVENIO MODIFICADO.</li>
        <li>LA NOTIFICACI&Oacute;N AL USUARIO SOBRE DICHAS MODIFICACIONES.</li>
        </ol>
        <p>DE ESTA FORMA, EL USUARIO EST&Aacute; DE ACUERDO EN REVISAR DICHO CONVENIO PERI&Oacute;DICAMENTE CON LA FINALIDAD DE MANTENERSE AL TANTO DE DICHAS MODIFICACIONES. NO OBSTANTE, LO ANTERIOR, CADA VEZ QUE EL USUARIO ACCEDA AL SITIO SE&Ntilde;ALADO SE CONSIDERAR&Aacute; COMO UNA ACEPTACI&Oacute;N ABSOLUTA A LAS MODIFICACIONES DEL PRESENTE CONVENIO.</p>
        <ol start="12">
        <li>SOBRE T&Eacute;RMINOS ADICIONALES</li>
        </ol>
        <p>OCASIONALMENTE,&nbsp;guapissima cosmetics&reg;&nbsp;PODR&Aacute; AGREGAR A LOS T&Eacute;RMINOS Y CONDICIONES DE USO DEL PRESENTE CONVENIO PROVISIONES ADICIONALES RELATIVAS A &Aacute;REAS ESPEC&Iacute;FICAS O NUEVOS SERVICIOS QUE SE PROPORCIONEN EN O A TRAV&Eacute;S DEL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>&nbsp;(EN LO SUBSECUENTE &laquo;T&Eacute;RMINOS ADICIONALES&raquo;), LOS CUALES SER&Aacute;N PUBLICADOS EN LAS &Aacute;REAS ESPEC&Iacute;FICAS O NUEVOS SERVICIOS DE DICHO SITIO PARA SU LECTURA Y ACEPTACI&Oacute;N. EL USUARIO RECONOCE Y ACEPTA QUE ESTOS T&Eacute;RMINOS ADICIONALES FORMAN PARTE INTEGRANTE DEL PRESENTE CONVENIO PARA TODOS LOS EFECTOS LEGALES A QUE HAYA LUGAR.</p>
        <ol start="13">
        <li>CESI&Oacute;N DE DERECHOS</li>
        </ol>
        <p>guapissima cosmetics&reg;&nbsp;PODR&Aacute;, EN CUALQUIER MOMENTO Y CUANDO AS&Iacute; LO ESTIME CONVENIENTE, CEDER TOTAL O PARCIALMENTE SUS DERECHOS Y OBLIGACIONES DERIVADOS DEL PRESENTE CONVENIO. EN VIRTUD DE DICHA CESI&Oacute;N,&nbsp;guapissima cosmetics&reg;&nbsp;QUEDAR&Aacute; LIBERADA DE CUALQUIER OBLIGACI&Oacute;N A FAVOR DEL USUARIO, ESTABLECIDA EN EL PRESENTE CONVENIO.</p>
        <ol start="14">
        <li>INDEMNIZACI&Oacute;N</li>
        </ol>
        <p>EL USUARIO EST&Aacute; DE ACUERDO EN INDEMNIZAR A&nbsp;guapissima cosmetics&reg;, SUS AFILIADOS, PROVEEDORES, VENDEDORES Y ASESORES POR CUALQUIER ACCI&Oacute;N, DEMANDA O RECLAMACI&Oacute;N (INCLUSO DE HONORARIOS DE ABOGADOS Y DE COSTAS JUDICIALES) DERIVADAS DE CUALQUIER INCUMPLIMIENTO POR PARTE DEL USUARIO AL PRESENTE CONVENIO; INCLUYENDO, SIN LIMITACI&Oacute;N DE ALGUNA DE LAS DERIVADAS DE:</p>
        <ol>
        <li>CUALQUIER ASPECTO RELATIVO AL USO DEL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a></li>
        <li>LA INFORMACI&Oacute;N CONTENIDA O DISPONIBLE EN O A TRAV&Eacute;S DE DICHO SITIO O DE INJURIAS, DIFAMACI&Oacute;N O CUALQUIER OTRA CONDUCTA VIOLATORIA DEL PRESENTE CONVENIO POR PARTE DEL USUARIO EN EL USO DE LA P&Aacute;GINA WEB SE&Ntilde;ALADA.</li>
        <li>LA VIOLACI&Oacute;N A LAS LEYES APLICABLES O TRATADOS INTERNACIONALES RELATIVOS A LOS DERECHOS DE AUTOR O PROPIEDAD INTELECTUAL, CONTENIDOS O DISPONIBLES EN, O A TRAV&Eacute;S DE DICHO SITIO WEB.</li>
        </ol>
        <ol start="15">
        <li>TERMINACI&Oacute;N</li>
        </ol>
        <p>guapissima cosmetics&reg;&nbsp;SE RESERVA EL DERECHO, A SU EXCLUSIVA DISCRECI&Oacute;N, Y SIN NECESIDAD DE AVISO O NOTIFICACI&Oacute;N AL USUARIO, PARA:</p>
        <ol>
        <li>TERMINAR DEFINITIVAMENTE EL PRESENTE CONVENIO.</li>
        <li>DESCONTINUAR O DEJAR DE PUBLICAR DEFINITIVAMENTE EL SITIO WEB&nbsp;<a href="HTTPS://guapissimaonline.COM.MX/">HTTPS://guapissimaonline.COM.MX/</a>&nbsp;SIN RESPONSABILIDAD ALGUNA PARA&nbsp;guapissima cosmetics&reg;, SUS AFILIADOS O PROVEEDORES.</li>
        </ol>
        <ol start="16">
        <li>SUBSISTENCIA</li>
        </ol>
        <p>ESTOS T&Eacute;RMINOS Y CONDICIONES DE USO, AS&Iacute; COMO LOS T&Eacute;RMINOS ADICIONALES, CONSTITUYEN EL ACUERDO &Iacute;NTEGRO ENTRE LAS PARTES, Y SUSTITUYE CUALQUIER OTRO ACUERDO O CONVENIO CELEBRADO CON ANTERIORIDAD. CUALQUIER CL&Aacute;USULA O PROVISI&Oacute;N DEL PRESENTE CONVENIO, AS&Iacute; COMO DE LOS T&Eacute;RMINOS ADICIONALES, LEGALMENTE DECLARADA INV&Aacute;LIDA, SER&Aacute; ELIMINADA O MODIFICADA A ELECCI&Oacute;N DE&nbsp;guapissima cosmetics&reg;, CON LA FINALIDAD DE CORREGIR SU VICIO O DEFECTO. SIN EMBARGO, EL RESTO DE LAS CL&Aacute;USULAS O PROVISIONES MANTENDR&Aacute;N SU FUERZA, OBLIGATORIEDAD Y VALIDEZ.</p>
        <ol start="17">
        <li>NO RENUNCIA DE DERECHOS</li>
        </ol>
        <p>LA INACTIVIDAD POR PARTE DE&nbsp;guapissima cosmetics&reg;, SUS AFILIADOS O PROVEEDORES AL EJERCICIO DE CUALQUIER DERECHO O ACCI&Oacute;N DERIVADOS DEL PRESENTE CONVENIO, EN NING&Uacute;N MOMENTO DEBER&Aacute; INTERPRETARSE COMO RENUNCIA A DICHOS DERECHOS O ACCIONES.</p>
        <ol start="18">
        <li>LEGISLACI&Oacute;N APLICABLE Y JURISDICCI&Oacute;N</li>
        </ol>
        <p>ESTE CONVENIO ESTAR&Aacute; SUJETO Y SER&Aacute; INTERPRETADO DE ACUERDO CON LAS LEYES Y ANTE LOS TRIBUNALES DEL ESTADO DE nuevo le&oacute;n, M&Eacute;XICO.</p>
        <ol start="19">
        <li>T&Eacute;RMINOS ADICIONALES</li>
        </ol>
        <p>LOS PRECIOS Y LAS ESPECIFICACIONES DE ESTA TIENDA VIRTUAL EST&Aacute;N SUJETAS A CAMBIO SIN PREVIO AVISO DEBIDO A POSIBLES RESTRICCIONES EN LAS IMPORTACIONES Y/O ESCASEZ DE CUALQUIERA DE SUS COMPONENTES. DEBIDO A LA DIN&Aacute;MICA DE NUESTRA INDUSTRIA, LA INFORMACI&Oacute;N AQU&Iacute; MOSTRADA PUEDE CONTENER ERRORES U OMISIONES, POR LO QUE NO NOS HACEMOS RESPONSABLES POR NING&Uacute;N DA&Ntilde;O QUE ESTO PUDIERA OCASIONAR. AL MOMENTO DE QUE SE CONFIRME SU PEDIDO, EL PAGO ES DE CONTADO:</p>
        <p>PAGO CON TARJETAS DE CR&Eacute;DITO O D&Eacute;BITO.</p>
        <p>Guapissima cosmetics&reg;&nbsp;SE RESERVA EL DERECHO DE CANCELAR CUALQUIER PAGO QUE NO CUMPLA CON LOS REQUISITOS QUE SOLICITE EL BANCO, ESTO SIGNIFICA QUE EN CIERTOS CASOS SE LE PUEDE PEDIR QUE NOS ENV&Iacute;E UNA COPIA DE SU IDENTIFICACI&Oacute;N OFICIAL Y/O COMPROBANTE DE DOMICILIO, AS&Iacute; COMO RFC, COPIA DEL ESTADO DE CUENTA DE SU TARJETA DE CR&Eacute;DITO O D&Eacute;BITO Y OTROS DOCUMENTOS QUE COMPRUEBEN SU IDENTIDAD. EN CASO DE CUALQUIER FALTA DE DOCUMENTOS SOLICITADO SU PAGO SER&Aacute; REVERTIDO.</p>
        <p>ENV&Iacute;OS A TODA LA REP&Uacute;BLICA.</p>
        <p>LOS PRODUCTOS EN PEDIDOS SE SURTEN EN EL ORDEN EN EL SON ACREDITADOS LOS PAGOS. LA EXISTENCIA EN EL SITIO WEB Y TIENDAS PUEDE VARIAR ENTRE EL MOMENTO EN EL CUAL SE REALIZA SU PEDIDO Y EL MOMENTO EN QUE SE APLICA SU PAGO.</p>
        <p>LOS PRODUCTOS DE CADA PEDIDO no SER&Aacute;N SEPARADOS DEL INVENTARIO DEL SITIO WEB Y TIENDAS HASTA QUE SE HAYA ACREDITADO EL PAGO DE LOS MISMOS, DEBIDO A QUE LA EXISTENCIA PUEDE VARIAR, EL PRODUCTO PUEDE DEJAR DE ESTAR DISPONIBLE EN EL LAPSO DE TIEMPO EN EL QUE SE ACREDITA EL PAGO, POR LO CUAL&nbsp;guapissima cosmetics&reg;&nbsp;NO PUDE GARANTIZAR LA ENTREGA DE LOS PRODUCTOS. SI ESTE FUERA EL CASO&nbsp;guapissima cosmetics&reg;&nbsp;SE COMPROMETE A HACER LA DEVOLUCI&Oacute;N TOTAL DEL PAGO DE LOS PRODUCTOS QUE NO SE PUEDAN SURTIR.</p>
        <p>LA MERCANC&Iacute;A VIAJAR&Aacute; POR RIESGO DEL CLIENTE.</p>
        <p>guapissima cosmetics&reg;&nbsp;Y LA PAQUETER&Iacute;A NO HAR&Aacute;N NINGUNA DEVOLUCI&Oacute;N NI PARCIAL NI TOTAL DE LOS PRODUCTOS ENVIADOS QUE NO CUENTEN CON SEGURO ANTES DE SER ENVIADOS Y PREVIAMENTE PAGADOS.</p>
        <p>GARANT&Iacute;AS Y DEVOLUCIONES.</p>
        <p><strong>GARANT&Iacute;AS:</strong></p>
        <p>LA GARANT&Iacute;A VAR&Iacute;A DE UN PRODUCTO A OTRO SEG&Uacute;N LA DESCRITA EN LA P&Oacute;LIZA DEL FABRICANTE, SIENDO ESTE EL &Uacute;NICO RESPONSABLE DEL CUMPLIMIENTO DE ESTA. EN CASO DE QUE LA MERCANC&Iacute;A PRESENTE ALG&Uacute;N DA&Ntilde;O O DEFECTO DE FABRICACI&Oacute;N EL CLIENTE PODR&Aacute; HACER V&Aacute;LIDA SU GARANT&Iacute;A EN LOS CENTROS DE SERVICIO DE&nbsp;guapissima cosmetics&reg;&nbsp;DURANTE LOS PRIMEROS SIETE D&Iacute;AS NATURALES POSTERIORES A LA FECHA DE COMPRA.</p>
        <p>TODO PRODUCTO QUE DEBA SER PROCESADO PARA TEMAS DE GARANT&Iacute;A DEBER&Aacute;N PRESENTAR EMPAQUES ORIGINALES (CAJA, BOLSA PL&Aacute;STICA, MANUALES, ACCESORIOS, TARJETA DE GARANT&Iacute;A, ETC.).</p>
        <p>ADICIONAL TODO PRODUCTO QUE SEA PROCESADO COMO UNA GARANT&Iacute;A VALIDA, TENDR&Aacute; QUE SER VALIDADO BAJO LAS BASES DE DEPRECIACI&Oacute;N SE&Ntilde;ALADAS A CONTINUACI&Oacute;N:</p>
        <p>EL TIEMPO SE TOMA EN CUENTA DESDE EL MOMENTO EN QUE SE GENERA LA VENTA INICIAL DEL PRODUCTO, EN CASOS DE SUSTITUCI&Oacute;N, REPARACI&Oacute;N DE MODELO ENTRE OTROS CASOS, SE TOMARA COMO FECHA INICIAL DE IGUAL MANERA EL PRIMER D&Iacute;A DE VENTA DEL PRODUCTO INICIAL.</p>
        <p>EXISTEN PRODUCTOS QUE NO PODR&Aacute;N SER RECIBIDOS PARA TRAMITE DE GARANT&Iacute;A EN LOS CENTROS DE SERVICIO DE&nbsp;guapissima cosmetics&reg;&nbsp;DEBIDO A QUE LA MARCA POR T&Eacute;RMINOS DE CALIDAD Y SERVICIO PIDE QUE SEAN PROCESADOS EN LOS CENTROS DE SERVICIO DE LA MARCA CORRESPONDIENTE, AL PRODUCTO QUE TENGA ALGUNA FALLA.</p>
        <p>PARA ESTE EFECTO LOS GASTOS DE ENV&Iacute;O Y SEGURO DE PRODUCTOS PARA REVISI&Oacute;N O PROCESAMIENTO DE LA GARANT&Iacute;A CORREN POR CUENTA Y RIESGO DEL CLIENTE.</p>
        <p>TODAS LAS GARANT&Iacute;AS SON SUJETAS A UNA REVISI&Oacute;N Y EN CASO DE CONTAR CON DA&Ntilde;O F&Iacute;SICO SE INVALIDAR&Aacute; LA GARANT&Iacute;A DE LOS PRODUCTOS DE MANERA INMEDIATA.</p>
        <p><strong>DEVOLUCIONES:</strong></p>
        <p>TODAS LAS DEVOLUCIONES DE PRODUCTO SON SUJETAS A APROBACI&Oacute;N SEG&Uacute;N LOS SIGUIENTES PROCESOS:</p>
        <p><em>PRIMER PROCESO:</em></p>
        <p>EL CLIENTE DEBER&Aacute; IDENTIFICAR LO SIGUIENTE:</p>
        <ul>
        <li>CAUSA QUE ORIGINA LA DEVOLUCI&Oacute;N (DE FORMA CLARA Y PRECISA)</li>
        <li>TIPO DE VENTA</li>
        <li>IDENTIFICAR LA FACTURA Y/O N&Uacute;MERO DE PEDIDO QUE AMPARA EL EQUIPO EN CUESTI&Oacute;N</li>
        <li>SOLICITUD POR ESCRITO V&Iacute;A CORREO ELECTR&Oacute;NICO A LA CUENTA&nbsp;<a href="mailto:CONTACTO@guapissima.COM.MX">CONTACTO@guapissima.COM.MX</a>&nbsp;LA PETICI&Oacute;N DE DEVOLUCI&Oacute;N.</li>
        </ul>
        <p><em>SEGUNDO PROCESO:</em></p>
        <ul>
        <li>EL EJECUTIVO DE VENTAS INTERNET REALIZAR&Aacute; LA GESTI&Oacute;N DE FIRMAS PARA AUTORIZACI&Oacute;N CON EL FABRICANTE.</li>
        <li>UNA VEZ AUTORIZADA LA SOLICITUD SE EMITE UN FOLIO DE DEVOLUCI&Oacute;N.</li>
        </ul>
        <p><em>TERCER PROCESO:</em></p>
        <ul>
        <li>EL FOLIO SE DA A CONOCER AL CLIENTE POR CORREO ELECTR&Oacute;NICO.</li>
        <li>LOS BULTOS QUE AMPARAN LA DEVOLUCI&Oacute;N DEBEN SER ROTULADOS CON EL FOLIO ASIGNADO, EN UN LUGAR VISIBLE Y DE FORMA LEGIBLE</li>
        <li>EL CLIENTE ES EL RESPONSABLE DE ASEGURAR QUE SE CUMPLA LO SIGUIENTE:</li>
        </ul>
        <ol>
        <li>EMPACADO CORRECTAMENTE (PROTECCI&Oacute;N ADECUADA CONTRA GOLPES, HUMEDAD, EST&Aacute;TICA, POLVO, CALOR EXCESIVO, ROBO, EXTRAV&Iacute;O, ETC.)</li>
        <li>COSTO DE FLETES DE ENV&Iacute;O A NUESTRAS INSTALACIONES EN LA CIUDAD DE monterrey, nuevo le&oacute;n O A ALG&Uacute;N OTRO PUNTO CONVENIDO CON EL EJECUTIVO DE VENTAS INTERNET QUE LE PUEDA CONVENIR AL CLIENTE PARA MAYOR RAPIDEZ, LOS SEGUROS, IMPUESTOS O CUALQUIER OTRO TR&Aacute;MITE, ESTOS A CARGO DEL CLIENTE</li>
        <li>CUALQUIER PROBLEMA LEGAL, ECOL&Oacute;GICO, ACCIDENTE, DE SEGURIDAD O DE CUALQUIER OTRO ASPECTO, QUE PUDIERA GENERAR EL ENV&Iacute;O DE LA DEVOLUCI&Oacute;N, ESTOS SER&Aacute;N A CARGO Y RESPONSABILIDAD DEL CLIENTE.</li>
        </ol>
        <p><em>CUARTO PROCESO:</em></p>
        <ul>
        <li>UNA VEZ QUE EL PRODUCTO LLEGUE A NUESTRAS INSTALACIONES, SE PROCEDER&Aacute; A LA REVISI&Oacute;N DEL PRODUCTO.</li>
        <li>EN CASO DE DA&Ntilde;O O FALTANTES, &Eacute;STOS SER&Aacute;N A CARGO DEL CLIENTE, EMITI&Eacute;NDOSE LA FACTURA CORRESPONDIENTE PARA GENERAR EL COBRO.</li>
        <li>CU&Aacute;NDO EXISTAN DOCUMENTOS QUE EL CLIENTE DEJE COMO GARANT&Iacute;A DE PAGO DE LOS EQUIPOS QUE PERTENECEN A LA DEVOLUCI&Oacute;N, ESTOS SER&Aacute;N ENTREGADOS UNA VEZ QUE SE CONCLUYA CON TODO EL PROCESO ANTERIOR.</li>
        </ul>
        <p>TODAS LAS DEVOLUCIONES SON SUJETAS A UN CARGO ADMINISTRATIVO SEG&Uacute;N LOS SIGUIENTES CRITERIOS:</p>
        <p>TODAS LAS DEVOLUCIONES SE HAR&Aacute;N DIRECTAMENTE A NUESTRAS INSTALACIONES MENCIONADAS A CONTINUACI&Oacute;N:</p>
        <p><strong>ATENCI&Oacute;N:</strong></p>
        <p>guapissima cosmetics<br /> ruiz cortines 6544<br /> mirador de las mitras.<br /> C&Oacute;DIGO POSTAL 66360<br /> monterrey, nuevo le&oacute;n, M&Eacute;XICO.<br /> <a href="mailto:CONTACTO@guapissima.COM.MX">CONTACTO@guapissima.COM.MX</a></p>
        <p>POR NING&Uacute;N MOTIVO SE ACEPTAR&Aacute; PRODUCTO EN DEVOLUCI&Oacute;N SI CUMPLE CON ALGUNO DE LOS SIGUIENTES CASOS:</p>
        <p>EL PRODUCTO FUE USADO.<br /> EL EMPAQUE O LAS CAJAS DE PRODUCTO CUENTAN CON ETIQUETAS NO ORIGINALES O EST&Eacute;N VIOLADAS; SE ENCUENTRA RAYADO, CON GOLPES, SUCIO O CON OTRA FORMA DE MALTRATO.<br /> EL EMPAQUE O LAS CAJAS NO SEAN ORIGINALES.<br /> EL PRODUCTO HAYA SIDO SOLICITADO SOBRE PEDIDO.<br /> EL PRODUCTO ES OBSOLETO O EST&Aacute; FUERA DE L&Iacute;NEA.<br /> EL PRODUCTO FUE VENDIDO COMO REMATE.</p>
        <p>SU PEDIDO, RECIBO Y/O FACTURA INCLUYA LA LEYENDA *SIN DEVOLUCI&Oacute;N Y/O CANCELACI&Oacute;N O ALGO SIMILAR QUE IMPLIQUE QUE SU PRODUCTO NO CUENTA CON DEVOLUCI&Oacute;N.</p>
        <p><em>INFORMACI&Oacute;N ADICIONAL</em></p>
        <p>TODO SISTEMA O IMAGEN PUDO HABER SIDO FOTOGRAFIADO CON OPCIONES ADICIONALES.</p>
        <p>LOS DOCUMENTOS DE C&Aacute;LCULOS EFECTUADOS SOBRE LOS SUBTOTALES Y TOTALES A PAGAR SON SOLAMENTE UNA REFERENCIA DE SU PEDIDO. NO ES UN COMPROBANTE FISCAL, NI PUEDE SER UTILIZADO COMO COMPROBANTE DE PAGO.</p>
        <p>EL DISE&Ntilde;O DEL LOGOTIPO Y NOMBRE DE&nbsp;guapissima cosmetics&reg;&nbsp;SON MARCAS REGISTRADAS DE&nbsp;mireya aide villarreal cardenas&nbsp;ES DECIR COPYRIGHT &copy; 2022 TODOS LOS DERECHOS RESERVADOS.</p>
        <p>&nbsp;</p>
</div>
